--Initial data for all pPOD instances
--The A, T, G, and C states


INSERT INTO `PPOD`.`CHARACTER_STATE` (LABEL,STATE_NUMBER,ID,PHYLO_CHARACTER_ID) VALUES ('A',0,2,1);
INSERT INTO `PPOD`.`CHARACTER_STATE` (LABEL,STATE_NUMBER,ID,PHYLO_CHARACTER_ID) VALUES ('C',1,3,1);
INSERT INTO `PPOD`.`CHARACTER_STATE` (LABEL,STATE_NUMBER,ID,PHYLO_CHARACTER_ID) VALUES ('G',2,4,1);
INSERT INTO `PPOD`.`CHARACTER_STATE` (LABEL,STATE_NUMBER,ID,PHYLO_CHARACTER_ID) VALUES ('T',3,5,1);


INSERT INTO `PPOD`.`DNA_CHARACTER` (ID) VALUES (1);


INSERT INTO `PPOD`.`DNA_STATE` (ID) VALUES (2);
INSERT INTO `PPOD`.`DNA_STATE` (ID) VALUES (3);
INSERT INTO `PPOD`.`DNA_STATE` (ID) VALUES (4);
INSERT INTO `PPOD`.`DNA_STATE` (ID) VALUES (5);


INSERT INTO `PPOD`.`PHYLO_CHARACTER` (PPOD_ID,LABEL,ID) VALUES ('46c155b2-cbc3-4a8b-9aed-57db315f07ad','DNA Character',1);
