CREATE TABLE ATTACHMENT
(
   PPOD_ID varchar(36) NOT NULL,
   BYTES_VALUE longblob,
   LABEL varchar(255),
   STRING_VALUE varchar(255),
   ID bigint PRIMARY KEY NOT NULL,
   PPOD_ENTITY_ID bigint NOT NULL,
   ATTACHMENT_TYPE_ID bigint NOT NULL
)
;
CREATE TABLE ATTACHMENT_NAMESPACE
(
   ID bigint PRIMARY KEY NOT NULL,
   VERSION int,
   LABEL varchar(64) NOT NULL
)
;
CREATE TABLE ATTACHMENT_TYPE
(
   ID bigint PRIMARY KEY NOT NULL,
   VERSION int,
   LABEL varchar(64) NOT NULL,
   ATTACHMENT_NAMESPACE_ID bigint NOT NULL
)
;
CREATE TABLE DNA_CELL
(
   POSITION int NOT NULL,
   TYPE int NOT NULL,
   ELEMENT int,
   ID bigint PRIMARY KEY NOT NULL,
   DNA_ROW_ID bigint NOT NULL
)
;
CREATE TABLE DNA_CELL_ELEMENTS
(
   DNA_CELL_ID bigint NOT NULL,
   ELEMENT int
)
;
CREATE TABLE DNA_MATRIX
(
   PPOD_ID varchar(36) NOT NULL,
   DESCRIPTION varchar(255),
   LABEL varchar(255) NOT NULL,
   ID bigint PRIMARY KEY NOT NULL,
   OTU_SET_ID bigint NOT NULL
)
;
CREATE TABLE DNA_MATRIX_DNA_ROW
(
   DNA_MATRIX_ID bigint NOT NULL,
   DNA_ROW_ID bigint NOT NULL,
   OTU_ID bigint NOT NULL,
   CONSTRAINT PRIMARY PRIMARY KEY (DNA_MATRIX_ID,OTU_ID)
)
;
CREATE TABLE DNA_MATRIX_VERSION_INFO
(
   DNA_MATRIX_ID bigint NOT NULL,
   VERSION_INFO_ID bigint NOT NULL,
   VERSION_INFO_POSITION int NOT NULL,
   CONSTRAINT PRIMARY PRIMARY KEY (DNA_MATRIX_ID,VERSION_INFO_POSITION)
)
;
CREATE TABLE DNA_ROW
(
   ID bigint PRIMARY KEY NOT NULL,
   PPOD_ENTITY_ID bigint NOT NULL
)
;
CREATE TABLE DNA_SEQUENCE
(
   ACCESSION varchar(255),
   DESCRIPTION varchar(255),
   NAME varchar(255),
   SEQUENCE longtext NOT NULL,
   ID bigint PRIMARY KEY NOT NULL,
   parent_ID bigint NOT NULL
)
;
CREATE TABLE DNA_SEQUENCE_PHRED_PHRAP_SCORES
(
   DNA_SEQUENCE_ID bigint NOT NULL,
   ELEMENT double
)
;
CREATE TABLE DNA_SEQUENCE_SET
(
   PPOD_ID varchar(36) NOT NULL,
   LABEL varchar(255) NOT NULL,
   ID bigint PRIMARY KEY NOT NULL,
   OTU_SET_ID bigint NOT NULL
)
;
CREATE TABLE DNA_SEQUENCE_SET_DNA_SEQUENCE
(
   DNA_SEQUENCE_SET_ID bigint NOT NULL,
   DNA_SEQUENCE_ID bigint NOT NULL,
   OTU_ID bigint NOT NULL,
   CONSTRAINT PRIMARY PRIMARY KEY (DNA_SEQUENCE_SET_ID,OTU_ID)
)
;
CREATE TABLE OTU
(
   PPOD_ID varchar(36) NOT NULL,
   LABEL varchar(255) NOT NULL,
   ID bigint PRIMARY KEY NOT NULL,
   OTU_SET_ID bigint NOT NULL,
   POSITION int
)
;
CREATE TABLE OTU_SET
(
   PPOD_ID varchar(36) NOT NULL,
   DESCRIPTION varchar(255),
   LABEL varchar(255) NOT NULL,
   ID bigint PRIMARY KEY NOT NULL,
   STUDY_ID bigint NOT NULL
)
;
CREATE TABLE PPOD_ENTITY
(
   ID bigint PRIMARY KEY NOT NULL,
   VERSION int,
   HAS_ATTACHMENTS bit NOT NULL,
   VERSION_INFO_ID bigint NOT NULL
)
;
CREATE TABLE STANDARD_CELL
(
   POSITION int NOT NULL,
   TYPE int NOT NULL,
   ID bigint PRIMARY KEY NOT NULL,
   STANDARD_STATE_ID bigint,
   STANDARD_ROW_ID bigint NOT NULL
)
;
CREATE TABLE STANDARD_CELL_STANDARD_STATE
(
   STANDARD_CELL_ID bigint NOT NULL,
   STANDARD_STATE_ID bigint NOT NULL,
   CONSTRAINT PRIMARY PRIMARY KEY (STANDARD_CELL_ID,STANDARD_STATE_ID)
)
;
CREATE TABLE STANDARD_CHARACTER
(
   PPOD_ID varchar(36) NOT NULL,
   LABEL varchar(255) NOT NULL,
   ID bigint PRIMARY KEY NOT NULL,
   STANDARD_MATRIX_ID bigint NOT NULL,
   POSITION int
)
;
CREATE TABLE STANDARD_MATRIX
(
   PPOD_ID varchar(36) NOT NULL,
   DESCRIPTION varchar(255),
   LABEL varchar(255) NOT NULL,
   ID bigint PRIMARY KEY NOT NULL,
   OTU_SET_ID bigint NOT NULL
)
;
CREATE TABLE STANDARD_MATRIX_STANDARD_ROW
(
   STANDARD_MATRIX_ID bigint NOT NULL,
   STANDARD_ROW_ID bigint NOT NULL,
   OTU_ID bigint NOT NULL,
   CONSTRAINT PRIMARY PRIMARY KEY (STANDARD_MATRIX_ID,OTU_ID)
)
;
CREATE TABLE STANDARD_MATRIX_VERSION_INFO
(
   STANDARD_MATRIX_ID bigint NOT NULL,
   VERSION_INFO_ID bigint NOT NULL,
   VERSION_INFO_POSITION int NOT NULL,
   CONSTRAINT PRIMARY PRIMARY KEY (STANDARD_MATRIX_ID,VERSION_INFO_POSITION)
)
;
CREATE TABLE STANDARD_ROW
(
   ID bigint PRIMARY KEY NOT NULL,
   STANDARD_MATRIX_ID bigint NOT NULL
)
;
CREATE TABLE STANDARD_STATE
(
   LABEL varchar(255) NOT NULL,
   STATE_NUMBER int NOT NULL,
   ID bigint PRIMARY KEY NOT NULL,
   STANDARD_CHARACTER_ID bigint NOT NULL
)
;
CREATE TABLE STUDY
(
   PPOD_ID varchar(36) NOT NULL,
   LABEL varchar(255) NOT NULL,
   ID bigint PRIMARY KEY NOT NULL
)
;
CREATE TABLE TREE
(
   PPOD_ID varchar(36) NOT NULL,
   LABEL varchar(255) NOT NULL,
   NEWICK longtext NOT NULL,
   ID bigint PRIMARY KEY NOT NULL,
   TREE_SET_ID bigint NOT NULL,
   POSITION int
)
;
CREATE TABLE TREE_SET
(
   PPOD_ID varchar(36) NOT NULL,
   LABEL varchar(255) NOT NULL,
   ID bigint PRIMARY KEY NOT NULL,
   OTU_SET_ID bigint NOT NULL
)
;
CREATE TABLE VERSION_INFO
(
   ID bigint PRIMARY KEY NOT NULL,
   VERSION int,
   CREATED timestamp NOT NULL,
   PPOD_VERSION bigint NOT NULL
)
;
ALTER TABLE ATTACHMENT
ADD CONSTRAINT FKA7E14523A76FEAE6
FOREIGN KEY (PPOD_ENTITY_ID)
REFERENCES ppod_entity(PPOD_ENTITY_ID)
;
ALTER TABLE ATTACHMENT
ADD CONSTRAINT FKA7E14523C4142B82
FOREIGN KEY (ATTACHMENT_TYPE_ID)
REFERENCES attachment_type(ATTACHMENT_TYPE_ID)
;
ALTER TABLE ATTACHMENT
ADD CONSTRAINT FKA7E14523829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
CREATE INDEX FKA7E14523C4142B82 ON ATTACHMENT(ATTACHMENT_TYPE_ID)
;
CREATE UNIQUE INDEX PRIMARY ON ATTACHMENT(ID)
;
CREATE INDEX FKA7E14523829B88F4 ON ATTACHMENT(ID)
;
CREATE UNIQUE INDEX PPOD_ID ON ATTACHMENT(PPOD_ID)
;
CREATE INDEX FKA7E14523A76FEAE6 ON ATTACHMENT(PPOD_ENTITY_ID)
;
CREATE UNIQUE INDEX PRIMARY ON ATTACHMENT_NAMESPACE(ID)
;
CREATE UNIQUE INDEX LABEL ON ATTACHMENT_NAMESPACE(LABEL)
;
ALTER TABLE ATTACHMENT_TYPE
ADD CONSTRAINT FK1C3DB8D6A7B438D2
FOREIGN KEY (ATTACHMENT_NAMESPACE_ID)
REFERENCES attachment_namespace(ATTACHMENT_NAMESPACE_ID)
;
CREATE INDEX FK1C3DB8D6A7B438D2 ON ATTACHMENT_TYPE(ATTACHMENT_NAMESPACE_ID)
;
CREATE INDEX LABEL_IDX ON ATTACHMENT_TYPE(LABEL)
;
CREATE UNIQUE INDEX PRIMARY ON ATTACHMENT_TYPE(ID)
;
ALTER TABLE DNA_CELL
ADD CONSTRAINT FK2A3B33AA829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
ALTER TABLE DNA_CELL
ADD CONSTRAINT FK2A3B33AA3C4EA36C
FOREIGN KEY (DNA_ROW_ID)
REFERENCES dna_row(DNA_ROW_ID)
;
CREATE UNIQUE INDEX PRIMARY ON DNA_CELL(ID)
;
CREATE INDEX FK2A3B33AA3C4EA36C ON DNA_CELL(DNA_ROW_ID)
;
CREATE INDEX FK2A3B33AA829B88F4 ON DNA_CELL(ID)
;
ALTER TABLE DNA_CELL_ELEMENTS
ADD CONSTRAINT FK35FF2DEC225BA4C8
FOREIGN KEY (DNA_CELL_ID)
REFERENCES dna_cell(DNA_CELL_ID)
;
CREATE INDEX FK35FF2DEC225BA4C8 ON DNA_CELL_ELEMENTS(DNA_CELL_ID)
;
ALTER TABLE DNA_MATRIX
ADD CONSTRAINT FK9918CC09829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
ALTER TABLE DNA_MATRIX
ADD CONSTRAINT FK9918CC0966F2217A
FOREIGN KEY (OTU_SET_ID)
REFERENCES otu_set(OTU_SET_ID)
;
CREATE UNIQUE INDEX PRIMARY ON DNA_MATRIX(ID)
;
CREATE INDEX FK9918CC09829B88F4 ON DNA_MATRIX(ID)
;
CREATE UNIQUE INDEX PPOD_ID ON DNA_MATRIX(PPOD_ID)
;
CREATE INDEX FK9918CC0966F2217A ON DNA_MATRIX(OTU_SET_ID)
;
ALTER TABLE DNA_MATRIX_DNA_ROW
ADD CONSTRAINT FKE2867C3CE80BB8E8
FOREIGN KEY (DNA_MATRIX_ID)
REFERENCES dna_matrix(DNA_MATRIX_ID)
;
ALTER TABLE DNA_MATRIX_DNA_ROW
ADD CONSTRAINT FKE2867C3C3C4EA36C
FOREIGN KEY (DNA_ROW_ID)
REFERENCES dna_row(DNA_ROW_ID)
;
ALTER TABLE DNA_MATRIX_DNA_ROW
ADD CONSTRAINT FKE2867C3C93E26F9
FOREIGN KEY (OTU_ID)
REFERENCES otu(OTU_ID)
;
CREATE INDEX FKE2867C3CE80BB8E8 ON DNA_MATRIX_DNA_ROW(DNA_MATRIX_ID)
;
CREATE INDEX FKE2867C3C3C4EA36C ON DNA_MATRIX_DNA_ROW(DNA_ROW_ID)
;
CREATE UNIQUE INDEX PRIMARY ON DNA_MATRIX_DNA_ROW
(
  DNA_MATRIX_ID,
  OTU_ID
)
;
CREATE INDEX FKE2867C3C93E26F9 ON DNA_MATRIX_DNA_ROW(OTU_ID)
;
CREATE UNIQUE INDEX DNA_ROW_ID ON DNA_MATRIX_DNA_ROW(DNA_ROW_ID)
;
ALTER TABLE DNA_MATRIX_VERSION_INFO
ADD CONSTRAINT FKA3BF544B834273CA
FOREIGN KEY (VERSION_INFO_ID)
REFERENCES version_info(VERSION_INFO_ID)
;
ALTER TABLE DNA_MATRIX_VERSION_INFO
ADD CONSTRAINT FKA3BF544BE80BB8E8
FOREIGN KEY (DNA_MATRIX_ID)
REFERENCES dna_matrix(DNA_MATRIX_ID)
;
CREATE UNIQUE INDEX PRIMARY ON DNA_MATRIX_VERSION_INFO
(
  DNA_MATRIX_ID,
  VERSION_INFO_POSITION
)
;
CREATE INDEX FKA3BF544B834273CA ON DNA_MATRIX_VERSION_INFO(VERSION_INFO_ID)
;
CREATE INDEX FKA3BF544BE80BB8E8 ON DNA_MATRIX_VERSION_INFO(DNA_MATRIX_ID)
;
ALTER TABLE DNA_ROW
ADD CONSTRAINT FK960222724323A2C4
FOREIGN KEY (PPOD_ENTITY_ID)
REFERENCES dna_matrix(PPOD_ENTITY_ID)
;
ALTER TABLE DNA_ROW
ADD CONSTRAINT FK96022272829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
CREATE INDEX FK96022272829B88F4 ON DNA_ROW(ID)
;
CREATE INDEX FK960222724323A2C4 ON DNA_ROW(PPOD_ENTITY_ID)
;
CREATE UNIQUE INDEX PRIMARY ON DNA_ROW(ID)
;
ALTER TABLE DNA_SEQUENCE
ADD CONSTRAINT FKF3FFB609829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
ALTER TABLE DNA_SEQUENCE
ADD CONSTRAINT FKF3FFB6092037477B
FOREIGN KEY (parent_ID)
REFERENCES dna_sequence_set(parent_ID)
;
CREATE UNIQUE INDEX PRIMARY ON DNA_SEQUENCE(ID)
;
CREATE INDEX FKF3FFB6092037477B ON DNA_SEQUENCE(parent_ID)
;
CREATE INDEX FKF3FFB609829B88F4 ON DNA_SEQUENCE(ID)
;
ALTER TABLE DNA_SEQUENCE_PHRED_PHRAP_SCORES
ADD CONSTRAINT FK28B80B1336D03D68
FOREIGN KEY (DNA_SEQUENCE_ID)
REFERENCES dna_sequence(DNA_SEQUENCE_ID)
;
CREATE INDEX FK28B80B1336D03D68 ON DNA_SEQUENCE_PHRED_PHRAP_SCORES(DNA_SEQUENCE_ID)
;
ALTER TABLE DNA_SEQUENCE_SET
ADD CONSTRAINT FKE1DFF90C829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
ALTER TABLE DNA_SEQUENCE_SET
ADD CONSTRAINT FKE1DFF90C66F2217A
FOREIGN KEY (OTU_SET_ID)
REFERENCES otu_set(OTU_SET_ID)
;
CREATE INDEX FKE1DFF90C66F2217A ON DNA_SEQUENCE_SET(OTU_SET_ID)
;
CREATE UNIQUE INDEX PRIMARY ON DNA_SEQUENCE_SET(ID)
;
CREATE INDEX FKE1DFF90C829B88F4 ON DNA_SEQUENCE_SET(ID)
;
CREATE UNIQUE INDEX PPOD_ID ON DNA_SEQUENCE_SET(PPOD_ID)
;
ALTER TABLE DNA_SEQUENCE_SET_DNA_SEQUENCE
ADD CONSTRAINT FK26A13A5C36D03D68
FOREIGN KEY (DNA_SEQUENCE_ID)
REFERENCES dna_sequence(DNA_SEQUENCE_ID)
;
ALTER TABLE DNA_SEQUENCE_SET_DNA_SEQUENCE
ADD CONSTRAINT FK26A13A5C712D9FD9
FOREIGN KEY (DNA_SEQUENCE_SET_ID)
REFERENCES dna_sequence_set(DNA_SEQUENCE_SET_ID)
;
ALTER TABLE DNA_SEQUENCE_SET_DNA_SEQUENCE
ADD CONSTRAINT FK26A13A5C93E26F9
FOREIGN KEY (OTU_ID)
REFERENCES otu(OTU_ID)
;
CREATE UNIQUE INDEX PRIMARY ON DNA_SEQUENCE_SET_DNA_SEQUENCE
(
  DNA_SEQUENCE_SET_ID,
  OTU_ID
)
;
CREATE INDEX FK26A13A5C36D03D68 ON DNA_SEQUENCE_SET_DNA_SEQUENCE(DNA_SEQUENCE_ID)
;
CREATE INDEX FK26A13A5C712D9FD9 ON DNA_SEQUENCE_SET_DNA_SEQUENCE(DNA_SEQUENCE_SET_ID)
;
CREATE INDEX FK26A13A5C93E26F9 ON DNA_SEQUENCE_SET_DNA_SEQUENCE(OTU_ID)
;
CREATE UNIQUE INDEX DNA_SEQUENCE_ID ON DNA_SEQUENCE_SET_DNA_SEQUENCE(DNA_SEQUENCE_ID)
;
ALTER TABLE OTU
ADD CONSTRAINT FK13310829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
ALTER TABLE OTU
ADD CONSTRAINT FK1331066F2217A
FOREIGN KEY (OTU_SET_ID)
REFERENCES otu_set(OTU_SET_ID)
;
CREATE INDEX FK13310829B88F4 ON OTU(ID)
;
CREATE UNIQUE INDEX PRIMARY ON OTU(ID)
;
CREATE UNIQUE INDEX PPOD_ID ON OTU(PPOD_ID)
;
CREATE INDEX FK1331066F2217A ON OTU(OTU_SET_ID)
;
ALTER TABLE OTU_SET
ADD CONSTRAINT FKE73D9A93829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
ALTER TABLE OTU_SET
ADD CONSTRAINT FKE73D9A93526A2499
FOREIGN KEY (STUDY_ID)
REFERENCES study(STUDY_ID)
;
CREATE UNIQUE INDEX PRIMARY ON OTU_SET(ID)
;
CREATE INDEX FKE73D9A93526A2499 ON OTU_SET(STUDY_ID)
;
CREATE INDEX FKE73D9A93829B88F4 ON OTU_SET(ID)
;
CREATE UNIQUE INDEX PPOD_ID ON OTU_SET(PPOD_ID)
;
ALTER TABLE PPOD_ENTITY
ADD CONSTRAINT FK52FA378D834273CA
FOREIGN KEY (VERSION_INFO_ID)
REFERENCES version_info(VERSION_INFO_ID)
;
CREATE UNIQUE INDEX PRIMARY ON PPOD_ENTITY(ID)
;
CREATE INDEX FK52FA378D834273CA ON PPOD_ENTITY(VERSION_INFO_ID)
;
ALTER TABLE STANDARD_CELL
ADD CONSTRAINT FK44B3D9A45066577E
FOREIGN KEY (STANDARD_ROW_ID)
REFERENCES standard_row(STANDARD_ROW_ID)
;
ALTER TABLE STANDARD_CELL
ADD CONSTRAINT FK44B3D9A4829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
ALTER TABLE STANDARD_CELL
ADD CONSTRAINT FK44B3D9A41C3A571E
FOREIGN KEY (STANDARD_STATE_ID)
REFERENCES standard_state(STANDARD_STATE_ID)
;
CREATE INDEX FK44B3D9A41C3A571E ON STANDARD_CELL(STANDARD_STATE_ID)
;
CREATE UNIQUE INDEX PRIMARY ON STANDARD_CELL(ID)
;
CREATE INDEX FK44B3D9A4829B88F4 ON STANDARD_CELL(ID)
;
CREATE INDEX FK44B3D9A45066577E ON STANDARD_CELL(STANDARD_ROW_ID)
;
ALTER TABLE STANDARD_CELL_STANDARD_STATE
ADD CONSTRAINT FK308D146A1C3A571E
FOREIGN KEY (STANDARD_STATE_ID)
REFERENCES standard_state(STANDARD_STATE_ID)
;
ALTER TABLE STANDARD_CELL_STANDARD_STATE
ADD CONSTRAINT FK308D146A913A72F6
FOREIGN KEY (STANDARD_CELL_ID)
REFERENCES standard_cell(STANDARD_CELL_ID)
;
CREATE INDEX FK308D146A1C3A571E ON STANDARD_CELL_STANDARD_STATE(STANDARD_STATE_ID)
;
CREATE UNIQUE INDEX PRIMARY ON STANDARD_CELL_STANDARD_STATE
(
  STANDARD_CELL_ID,
  STANDARD_STATE_ID
)
;
CREATE INDEX FK308D146A913A72F6 ON STANDARD_CELL_STANDARD_STATE(STANDARD_CELL_ID)
;
ALTER TABLE STANDARD_CHARACTER
ADD CONSTRAINT FK16564C07829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
ALTER TABLE STANDARD_CHARACTER
ADD CONSTRAINT FK16564C071A6FB396
FOREIGN KEY (STANDARD_MATRIX_ID)
REFERENCES standard_matrix(STANDARD_MATRIX_ID)
;
CREATE UNIQUE INDEX PRIMARY ON STANDARD_CHARACTER(ID)
;
CREATE INDEX FK16564C07829B88F4 ON STANDARD_CHARACTER(ID)
;
CREATE INDEX FK16564C071A6FB396 ON STANDARD_CHARACTER(STANDARD_MATRIX_ID)
;
CREATE UNIQUE INDEX PPOD_ID ON STANDARD_CHARACTER(PPOD_ID)
;
ALTER TABLE STANDARD_MATRIX
ADD CONSTRAINT FKF7FFDB83829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
ALTER TABLE STANDARD_MATRIX
ADD CONSTRAINT FKF7FFDB8366F2217A
FOREIGN KEY (OTU_SET_ID)
REFERENCES otu_set(OTU_SET_ID)
;
CREATE UNIQUE INDEX PRIMARY ON STANDARD_MATRIX(ID)
;
CREATE INDEX FKF7FFDB8366F2217A ON STANDARD_MATRIX(OTU_SET_ID)
;
CREATE UNIQUE INDEX PPOD_ID ON STANDARD_MATRIX(PPOD_ID)
;
CREATE INDEX FKF7FFDB83829B88F4 ON STANDARD_MATRIX(ID)
;
ALTER TABLE STANDARD_MATRIX_STANDARD_ROW
ADD CONSTRAINT FK343970745066577E
FOREIGN KEY (STANDARD_ROW_ID)
REFERENCES standard_row(STANDARD_ROW_ID)
;
ALTER TABLE STANDARD_MATRIX_STANDARD_ROW
ADD CONSTRAINT FK343970741A6FB396
FOREIGN KEY (STANDARD_MATRIX_ID)
REFERENCES standard_matrix(STANDARD_MATRIX_ID)
;
ALTER TABLE STANDARD_MATRIX_STANDARD_ROW
ADD CONSTRAINT FK3439707493E26F9
FOREIGN KEY (OTU_ID)
REFERENCES otu(OTU_ID)
;
CREATE INDEX FK343970741A6FB396 ON STANDARD_MATRIX_STANDARD_ROW(STANDARD_MATRIX_ID)
;
CREATE INDEX FK343970745066577E ON STANDARD_MATRIX_STANDARD_ROW(STANDARD_ROW_ID)
;
CREATE UNIQUE INDEX STANDARD_ROW_ID ON STANDARD_MATRIX_STANDARD_ROW(STANDARD_ROW_ID)
;
CREATE UNIQUE INDEX PRIMARY ON STANDARD_MATRIX_STANDARD_ROW
(
  STANDARD_MATRIX_ID,
  OTU_ID
)
;
CREATE INDEX FK3439707493E26F9 ON STANDARD_MATRIX_STANDARD_ROW(OTU_ID)
;
ALTER TABLE STANDARD_MATRIX_VERSION_INFO
ADD CONSTRAINT FK96BABB11834273CA
FOREIGN KEY (VERSION_INFO_ID)
REFERENCES version_info(VERSION_INFO_ID)
;
ALTER TABLE STANDARD_MATRIX_VERSION_INFO
ADD CONSTRAINT FK96BABB111A6FB396
FOREIGN KEY (STANDARD_MATRIX_ID)
REFERENCES standard_matrix(STANDARD_MATRIX_ID)
;
CREATE INDEX FK96BABB111A6FB396 ON STANDARD_MATRIX_VERSION_INFO(STANDARD_MATRIX_ID)
;
CREATE INDEX FK96BABB11834273CA ON STANDARD_MATRIX_VERSION_INFO(VERSION_INFO_ID)
;
CREATE UNIQUE INDEX PRIMARY ON STANDARD_MATRIX_VERSION_INFO
(
  STANDARD_MATRIX_ID,
  VERSION_INFO_POSITION
)
;
ALTER TABLE STANDARD_ROW
ADD CONSTRAINT FK233FD538829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
ALTER TABLE STANDARD_ROW
ADD CONSTRAINT FK233FD5381A6FB396
FOREIGN KEY (STANDARD_MATRIX_ID)
REFERENCES standard_matrix(STANDARD_MATRIX_ID)
;
CREATE INDEX FK233FD538829B88F4 ON STANDARD_ROW(ID)
;
CREATE INDEX FK233FD5381A6FB396 ON STANDARD_ROW(STANDARD_MATRIX_ID)
;
CREATE UNIQUE INDEX PRIMARY ON STANDARD_ROW(ID)
;
ALTER TABLE STANDARD_STATE
ADD CONSTRAINT FK52AF7C6FBD568E1E
FOREIGN KEY (STANDARD_CHARACTER_ID)
REFERENCES standard_character(STANDARD_CHARACTER_ID)
;
ALTER TABLE STANDARD_STATE
ADD CONSTRAINT FK52AF7C6F829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
CREATE INDEX FK52AF7C6F829B88F4 ON STANDARD_STATE(ID)
;
CREATE INDEX FK52AF7C6FBD568E1E ON STANDARD_STATE(STANDARD_CHARACTER_ID)
;
CREATE UNIQUE INDEX PRIMARY ON STANDARD_STATE(ID)
;
ALTER TABLE STUDY
ADD CONSTRAINT FK4B915A9829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
CREATE UNIQUE INDEX PRIMARY ON STUDY(ID)
;
CREATE UNIQUE INDEX PPOD_ID ON STUDY(PPOD_ID)
;
CREATE INDEX FK4B915A9829B88F4 ON STUDY(ID)
;
ALTER TABLE TREE
ADD CONSTRAINT FK276B9ED3EDF17C
FOREIGN KEY (TREE_SET_ID)
REFERENCES tree_set(TREE_SET_ID)
;
ALTER TABLE TREE
ADD CONSTRAINT FK276B9E829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
CREATE UNIQUE INDEX PRIMARY ON TREE(ID)
;
CREATE INDEX FK276B9ED3EDF17C ON TREE(TREE_SET_ID)
;
CREATE UNIQUE INDEX PPOD_ID ON TREE(PPOD_ID)
;
CREATE INDEX FK276B9E829B88F4 ON TREE(ID)
;
ALTER TABLE TREE_SET
ADD CONSTRAINT FK8158DC2166F2217A
FOREIGN KEY (OTU_SET_ID)
REFERENCES otu_set(OTU_SET_ID)
;
ALTER TABLE TREE_SET
ADD CONSTRAINT FK8158DC21829B88F4
FOREIGN KEY (ID)
REFERENCES ppod_entity(ID)
;
CREATE UNIQUE INDEX PRIMARY ON TREE_SET(ID)
;
CREATE INDEX FK8158DC2166F2217A ON TREE_SET(OTU_SET_ID)
;
CREATE UNIQUE INDEX PPOD_ID ON TREE_SET(PPOD_ID)
;
CREATE INDEX FK8158DC21829B88F4 ON TREE_SET(ID)
;
CREATE UNIQUE INDEX PRIMARY ON VERSION_INFO(ID)
;
CREATE UNIQUE INDEX PPOD_VERSION ON VERSION_INFO(PPOD_VERSION)
;
